spring.application.name=cinema_manager


# ===============================
# DATABASE CONFIG
# ===============================

# Kết nối MySQL
# createDatabaseIfNotExist=true:
# nếu DB chưa tồn tại thì tự tạo
spring.datasource.url=jdbc:mysql://localhost:3306/cinema_manager?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8

# Username MySQL
spring.datasource.username=root

# Password MySQL
spring.datasource.password=loc123456


# ===============================
# JPA / HIBERNATE
# ===============================

# Hibernate tự update table theo entity
# update:
# - tạo bảng nếu chưa có
# - update cột mới
# - không xoá dữ liệu cũ
spring.jpa.hibernate.ddl-auto=update

# Hiển thị câu SQL trong console
spring.jpa.show-sql=true

# Format SQL đẹp, dễ đọc hơn
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# THYMELEAF
# ===============================

# Tắt cache Thymeleaf
# sửa HTML không cần restart server
spring.thymeleaf.cache=false


# ===============================
# SQL INIT / SEED DATA
# ===============================

# Luôn chạy data.sql khi startup
spring.sql.init.mode=always

# Đường dẫn file seed data
spring.sql.init.data-locations=classpath:data.sql

# Đợi Hibernate tạo table xong
# rồi mới chạy data.sql
spring.jpa.defer-datasource-initialization=true